# BEGIN MYCONFIG BLACKNPINK
resolution max
enable_mouse
mouse_size 24
mouse_speed 8

banner themes/blacknpink/background.png
banner_scale fillscreen
icons_dir themes/blacknpink/icons
selection_big themes/blacknpink/selection-big.png
selection_small themes/blacknpink/selection-small.png
font themes/blacknpink/font.png

big_icon_size 128
small_icon_size 48
hideui hints badges
showtools shutdown,reboot,firmware
# END MYCONFIG BLACKNPINK
