;;; test-emacs-dired.el --- Dired workspace selection -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'ls-lisp)
(let ((lisp (expand-file-name "../dotfiles/emacs/.config/emacs/lisp/"
                              (file-name-directory (or load-file-name buffer-file-name)))))
  (add-to-list 'load-path lisp)
  (add-to-list 'load-path (expand-file-name "atelier" lisp)))
(require 'dired-atelier)
(require 'universel-atelier)
(dired-atelier-setup)

(defmacro atelier-dired-test-with-directories (&rest body)
  (declare (indent 0))
  `(let* ((root (make-temp-file "atelier-dired-test-" t))
          (one (expand-file-name "one" root))
          (two (expand-file-name "two" root))
          (file (expand-file-name "file.txt" root))
          (old (list :id "old" :name "old" :destination "local" :path root
                     :status 'running :entries nil))
          (atelier-workspaces (list old))
          (atelier-content-live-buffers (make-hash-table :test #'equal))
          (atelier-change-hook nil)
          (atelier-workspace-created-hook nil)
          (atelier-directory-function #'atelier-default-directory)
          (atelier-directory-target-function #'atelier-default-directory-target)
          (atelier-close-without-asking t)
          (ls-lisp-use-insert-directory-program nil)
          (previous (frame-parameter nil 'atelier-workspace-id))
          (buffers (buffer-list)))
     (unwind-protect
         (save-window-excursion
           (make-directory one)
           (make-directory two)
           (with-temp-file file (insert "file"))
           (atelier-select-workspace old)
           ,@body)
       (set-frame-parameter nil 'atelier-workspace-id previous)
       (dolist (buffer (buffer-list))
         (unless (memq buffer buffers) (kill-buffer buffer)))
       (delete-directory root t))))

(ert-deftest atelier-dired-native-workspace-flags-add-separate-workspaces ()
  (atelier-dired-test-with-directories
    (switch-to-buffer (dired-noselect root))
    (dired-goto-file one) (atelier-dired-flag-workspace 1)
    (dired-goto-file two) (atelier-dired-flag-workspace 1)
    (should (equal atelier-workspaces (list old)))
    (should (equal (atelier-dired-workspace-flags) (list one two)))
    (let ((source (current-buffer)))
      (cl-letf (((symbol-function 'read-string)
                 (lambda (_prompt suggestion &rest _) suggestion)))
        (atelier-dired-execute-flags))
      (should (equal (mapcar (lambda (workspace) (plist-get workspace :name))
                             atelier-workspaces)
                     '("old" "one" "two")))
      (should (equal (plist-get (atelier-current-workspace) :name) "two"))
      (dolist (pair (list (cons "one" one) (cons "two" two)))
        (let* ((workspace (atelier-workspace-get (car pair)))
               (entry (car (atelier-workspace-entries workspace)))
               (buffer (atelier-entry-live-buffer entry)))
          (should (equal (directory-file-name (plist-get workspace :path)) (cdr pair)))
          (should (buffer-live-p buffer))
          (with-current-buffer buffer
            (should (derived-mode-p 'dired-mode))
            (should (equal (directory-file-name default-directory) (cdr pair))))))
      (with-current-buffer source
        (should-not (atelier-dired-workspace-flags))))))

(ert-deftest atelier-dired-execution-does-not-use-ordinary-marks-or-point ()
  (atelier-dired-test-with-directories
    (switch-to-buffer (dired-noselect root))
    (dired-goto-file one) (dired-mark 1)
    (dired-goto-file two)
    (atelier-dired-execute-flags)
    (should (equal atelier-workspaces (list old)))
    (should (equal (dired-get-marked-files nil 'marked) (list one)))))

(ert-deftest atelier-dired-file-flag-rejection-retains-ordinary-marks ()
  (atelier-dired-test-with-directories
    (switch-to-buffer (dired-noselect root))
    (dired-goto-file one) (dired-mark 1)
    (dired-goto-file file) (dired-mark 1)
    (dired-goto-file file)
    (should-error (atelier-dired-flag-workspace 1) :type 'user-error)
    (should-not (atelier-dired-workspace-flags))
    (should (equal atelier-workspaces (list old)))
    (should (equal (sort (dired-get-marked-files) #'string-lessp)
                   (sort (list one file) #'string-lessp)))))

(ert-deftest atelier-directory-api-cancellation-keeps-original-workspace-and-view ()
  (atelier-dired-test-with-directories
    (switch-to-buffer (dired-noselect root))
    (let ((source (current-buffer)) (calls 0))
      (cl-letf (((symbol-function 'read-string)
                 (lambda (_prompt suggestion &rest _)
                   (if (= (cl-incf calls) 2) (signal 'quit nil) suggestion))))
        (should (eq (condition-case nil
                        (progn (atelier-add-workspaces (list one two)) nil)
                      (quit 'cancelled))
                    'cancelled)))
      (should (equal atelier-workspaces (list old)))
      (should (eq (atelier-current-workspace) old))
      (should (eq (current-buffer) source))
      (should-not (cl-find-if
                   (lambda (buffer)
                     (with-current-buffer buffer
                       (and (derived-mode-p 'dired-mode)
                            (equal (directory-file-name default-directory) one))))
                   (buffer-list))))))

(ert-deftest atelier-directory-api-second-open-failure-publishes-no-additions ()
  (atelier-dired-test-with-directories
    (switch-to-buffer (dired-noselect root))
    (let ((source (current-buffer))
          (open (symbol-function 'atelier-new-dired-buffer)))
      (cl-letf (((symbol-function 'read-string)
                 (lambda (_prompt suggestion &rest _) suggestion))
                ((symbol-function 'atelier-new-dired-buffer)
                 (lambda (directory &rest arguments)
                   (if (equal (directory-file-name directory) two)
                       (error "Directory became unavailable")
                     (apply open directory arguments)))))
        (should-error (atelier-add-workspaces (list one two))))
      (should (equal atelier-workspaces (list old)))
      (should (eq (atelier-current-workspace) old))
      (should (eq (current-buffer) source))
      (should-not (cl-find-if
                   (lambda (buffer)
                     (with-current-buffer buffer
                       (and (derived-mode-p 'dired-mode)
                            (equal (directory-file-name default-directory) one))))
                   (buffer-list))))))

(ert-deftest atelier-dired-picker-returns-workspace-flags-without-inserting-a-row ()
  (atelier-dired-test-with-directories
    (let ((selection
           (cl-letf (((symbol-function 'recursive-edit)
                      (lambda ()
                        (should-not (string-match-p "Select this directory" (buffer-string)))
                        (dired-goto-file one) (atelier-dired-flag-workspace 1)
                        (dired-goto-file two) (atelier-dired-flag-workspace 1)
                        (catch 'selected
                          (cl-letf (((symbol-function 'exit-recursive-edit)
                                     (lambda () (throw 'selected t))))
                            (atelier-dired-execute-flags))))))
             (atelier-read-directories-with-dired root t))))
      (should (equal selection (list one two)))
      (should (equal atelier-workspaces (list old))))))

(ert-deftest atelier-dired-edit-picker-rejects-multiple-directories ()
  (atelier-dired-test-with-directories
    (switch-to-buffer (dired-noselect root))
    (dired-goto-file one) (atelier-dired-flag-workspace 1)
    (dired-goto-file two) (atelier-dired-flag-workspace 1)
    (let ((atelier-directory-chooser-mode t)
          (atelier-directory-chooser-multiple nil))
      (should-error (atelier-dired-execute-flags) :type 'user-error))
    (should (equal atelier-workspaces (list old)))))

(ert-deftest atelier-dired-deletion-first-adds-only-surviving-workspace-directories ()
  (atelier-dired-test-with-directories
    (let ((child (expand-file-name "child" one)) events)
      (make-directory child)
      (switch-to-buffer (dired-noselect root))
      (dired-insert-subdir one)
      (dired-goto-file child) (atelier-dired-flag-workspace 1)
      (dired-goto-file two) (atelier-dired-flag-workspace 1)
      (dired-goto-file one) (dired-flag-file-deletion 1)
      (cl-letf (((symbol-function 'dired-do-flagged-delete)
                 (lambda (&rest _)
                   (push 'deletion events)
                   ;; Simulate the native deletion boundary on owned fixtures.
                   (delete-directory one t)
                   (dired-delete-entry one)))
                ((symbol-function 'read-string)
                 (lambda (_prompt suggestion &rest _)
                   (push 'addition events)
                   (should-not (file-directory-p child))
                   suggestion)))
        (atelier-dired-execute-flags))
      (should (equal (nreverse events) '(deletion addition)))
      (should-not (atelier-workspace-get "child"))
      (should (atelier-workspace-get "two"))
      (should (= (length atelier-workspaces) 2)))))

(ert-deftest atelier-dired-declined-deletion-keeps-other-marks-and-adds-workspaces ()
  (atelier-dired-test-with-directories
    (switch-to-buffer (dired-noselect root))
    (dired-goto-file one) (dired-mark 1)
    (dired-goto-file file) (dired-flag-file-deletion 1)
    (dired-goto-file two) (atelier-dired-flag-workspace 1)
    (let ((source (current-buffer)))
      (cl-letf (((symbol-function 'dired-do-flagged-delete) #'ignore)
                ((symbol-function 'read-string)
                 (lambda (_prompt suggestion &rest _) suggestion)))
        (atelier-dired-execute-flags))
      (should (atelier-workspace-get "two"))
      (with-current-buffer source
        (should-not (atelier-dired-workspace-flags))
        (should (equal (dired-get-marked-files nil 'marked) (list one)))
        (let ((dired-marker-char dired-del-marker))
          (should (equal (dired-get-marked-files nil 'marked) (list file))))))))

(ert-deftest atelier-dired-cancelled-workspace-addition-retains-workspace-flags ()
  (atelier-dired-test-with-directories
    (switch-to-buffer (dired-noselect root))
    (dired-goto-file one) (atelier-dired-flag-workspace 1)
    (let ((source (current-buffer)))
      (cl-letf (((symbol-function 'read-string) (lambda (&rest _) (signal 'quit nil))))
        (should (eq (condition-case nil
                        (progn (atelier-dired-execute-flags) nil)
                      (quit 'cancelled))
                    'cancelled)))
      (should (equal atelier-workspaces (list old)))
      (should (eq (current-buffer) source))
      (should (equal (atelier-dired-workspace-flags) (list one))))))

(ert-deftest atelier-directory-targets-retain-ssh-port-and-wsl-destination ()
  (dolist (pair '(("/ssh:alice@host#2222:/project/" "alice@host#2222" "/project/" posix nil)
                  ("/wsl:Ubuntu:/project/" "Ubuntu" "/project/" wsl nil)))
    (should (equal (atelier-default-directory-target (car pair)) (cdr pair)))))

(ert-deftest atelier-directory-targets-retain-mounted-windows-connection ()
  (let* ((workspace '(:destination "alice@host#2222" :platform windows
                     :mount-root "/C:/" :path "/C:/parent/"))
         (atelier-workspaces (list workspace))
         (universel-atelier-state-directory temporary-file-directory)
         (environment (universel-atelier-environment workspace))
         (mount (universel-mount-point environment universel-atelier-state-directory)))
    (cl-letf (((symbol-function 'universel--ensure-mount)
               (lambda (&rest _) (ert-fail "Target conversion must not open a connection"))))
      (should (equal (universel-atelier-directory-target (expand-file-name "child/" mount))
                     '("alice@host#2222" "/C:/child/" windows "/C:/"))))))

(ert-run-tests-batch-and-exit)
