;;; test-emacs-aipanel-ordinary.el --- Standalone panel integration tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'subr-x)
(defgroup myconfig nil "Test configuration." :group 'environment)
(provide 'myconfig-core)
(provide 'ghostel)
(provide 'evil-ghostel)
(defvar myconfig-data-directory temporary-file-directory)
(defvar ghostel-char-mode-map (make-sparse-keymap))
(let ((lisp (expand-file-name "../dotfiles/emacs/.config/emacs/lisp/"
                              (file-name-directory (or load-file-name buffer-file-name)))))
  (add-to-list 'load-path lisp)
  (add-to-list 'load-path (expand-file-name "atelier" lisp))
  (dolist (file '("atelier/atelier.el" "atelier/ghostel-atelier.el" "myconfig-terminal.el"
                  "aipan.el" "atelier/aipanel-atelier.el"))
    (load (expand-file-name file lisp) nil t)))

(setq ghostel-atelier-buffer-started-hook '(myconfig-terminal-enter-input))
(myconfig-aipanel-setup)

(ert-deftest aipanel-ordinary-discovers-and-builds-pi-launch ()
  (let ((directory (make-temp-file "aipanel-pi-" t)))
    (unwind-protect
        (let* ((program (expand-file-name "pi" directory))
               (exec-path (list directory))
               (owner (list :location 'host :directory directory
                            :emacs-directory directory)))
          (with-temp-file program (insert "#!/bin/sh\nexit 0\n"))
          (set-file-modes program #o700)
          (let* ((candidates (aipanel-default-candidates owner))
                 (selection (cdar candidates)))
            (should (= (length candidates) 1))
            (should (eq (plist-get (plist-get selection :agent) :id) 'pi))
            (dolist (mini '(nil t))
              (should (equal (aipanel-default-command owner selection mini)
                             (list :program "pi" :arguments nil
                                   :directory directory))))))
      (delete-directory directory t))))

(ert-deftest myconfig-terminal-automatic-evil-activation-preserves-char-input ()
  (with-temp-buffer
    (setq major-mode 'ghostel-mode)
    (setq-local ghostel--input-mode 'char)
    (let ((disabled 0))
      (cl-letf (((symbol-function 'myconfig-terminal-enter-input)
                 (lambda () (cl-incf disabled))))
        (set (make-local-variable 'evil-local-mode) t)
        (myconfig-terminal-keep-input)
        (should (= disabled 1))
        (setq ghostel--input-mode 'emacs)
        (myconfig-terminal-keep-input)
        (should (= disabled 1))))))

(ert-deftest aipanel-ordinary-atelier-exclusion-has-a-public-lifecycle ()
  (let ((atelier-internal-buffers (make-hash-table :test #'eq)))
    (with-temp-buffer
      (rename-buffer "panel-exclusion-test" t)
      (let ((workspace '(:id "work")))
        (should (atelier-buffer-ownable-p (current-buffer) workspace))
        (atelier-set-buffer-excluded t)
        (should-not (atelier-buffer-ownable-p (current-buffer) workspace))
        (atelier-set-buffer-excluded nil)
        (should (atelier-buffer-ownable-p (current-buffer) workspace))))))

(ert-deftest aipanel-ordinary-owner-follows-source-not-selected-workspace ()
  (with-temp-buffer
    (setq default-directory "/ssh:alice@host#2222:/home/work/")
    (let ((source (current-buffer))
          (workspace '(:id "work" :platform wsl :destination "Ubuntu")))
      (cl-letf (((symbol-function 'atelier-current-workspace) (lambda (&rest _) workspace))
                (atelier-execution-directory-function
                 (lambda (_workspace directory) (concat "/mnt" directory))))
        (let ((owner (aipanel-atelier-owner)))
          (should (eq (plist-get owner :id) source))
          (should (eq (plist-get owner :source-buffer) source))
          (should (equal (plist-get owner :directory) "/home/work/"))
          (should (eq (plist-get owner :location) 'ssh))
          (should (equal (plist-get owner :destination) "alice@host")))))))

(ert-deftest aipanel-ordinary-terminal-has-no-atelier-job-or-entry ()
  (let ((source (generate-new-buffer " *panel-source*"))
        (aipanel-sessions (make-hash-table :test #'eq))
        (aipanel-buffer-created-hook nil)
        (aipanel-buffer-exited-hook nil)
        (atelier-internal-buffers (make-hash-table :test #'eq))
        panel)
    (unwind-protect
        (progn
          (aipanel-atelier-setup)
          (should (memq #'myconfig-aipanel-activate
                        aipanel-window-change-hook))
          (with-current-buffer source
            (setq default-directory "/tmp/")
            (let ((owner (aipanel-default-owner))
                  (selection '(:agent (:id fx :name "fx" :program "fx") :location host)))
              (cl-letf (((symbol-function 'ghostel-exec)
                         (lambda (buffer _program _arguments identity)
                           (should (equal identity '((kind . aipanel))))
                           (with-current-buffer buffer
                             (setq major-mode 'ghostel-mode
                                   ghostel--input-mode 'semi-char)
                             (use-local-map (make-sparse-keymap)))))
                        ((symbol-function 'ghostel-char-mode)
                         (lambda ()
                           (setq ghostel--input-mode 'char)
                           (use-local-map ghostel-char-mode-map)))
                        ((symbol-function 'atelier-register-job-buffer)
                         (lambda (&rest _) (ert-fail "Panel registered an Atelier job")))
                        ((symbol-function 'atelier-register-buffer)
                         (lambda (&rest _) (ert-fail "Panel registered an Atelier entry"))))
                (define-key ghostel-char-mode-map (kbd "C-x") #'ghostel--send-event)
                (define-key ghostel-char-mode-map (kbd "C-p") #'ghostel--send-event)
                (setq panel (aipanel-start owner nil selection))
                (with-current-buffer panel
                  (should (eq ghostel--input-mode 'char))
                  (should (eq (key-binding (kbd "C-x")) #'ghostel--send-event))
                  (should (eq (key-binding (kbd "C-p")) #'ghostel--send-event)))
                (should (eq (plist-get (buffer-local-value 'aipanel-owner panel) :source-buffer)
                            source))
                (should (gethash panel atelier-internal-buffers))
                (should-not (atelier-buffer-ownable-p panel '(:id "work")))
                (should (eq (gethash source aipanel-sessions) panel))
                (with-current-buffer panel (aipanel-cleanup-buffer panel))
                (should-not (gethash panel atelier-internal-buffers))
                (should-not (gethash source aipanel-sessions))))))
      (dolist (buffer (list source panel))
        (when (buffer-live-p buffer) (kill-buffer buffer))))))

(ert-deftest aipanel-ordinary-toggles-one-source-without-sharing ()
  (save-window-excursion
    (let ((source (generate-new-buffer " *panel-one*"))
          (other (generate-new-buffer " *panel-two*"))
          (panel (generate-new-buffer " *panel-terminal*"))
          (aipanel-sessions (make-hash-table :test #'eq))
          (aipanel-owner-function #'aipanel-default-owner)
          (real-live (symbol-function 'aipanel-live-buffer))
          (aipanel-window-change-hook nil)
          (aipanel-context-function (lambda (&rest _) nil)))
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (cl-letf (((symbol-function 'aipanel-live-buffer) (lambda (_owner) panel))
                      ((symbol-function 'aipanel-start)
                       (lambda (&rest _) (ert-fail "Unexpected second panel"))))
              (aipanel-toggle)
              (should (eq (window-buffer (selected-window)) panel))
              (should (window-parameter (selected-window) 'window-side))
              (select-window (window-main-window))
              (switch-to-buffer source)
              (aipanel-toggle)
              (should-not (get-buffer-window panel))
              (switch-to-buffer other)
              (let ((aipanel-sessions (make-hash-table :test #'eq)))
                (should-not (funcall real-live (aipanel-default-owner))))))
        (dolist (buffer (list source other panel))
          (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest aipanel-ordinary-process-exit-closes-its-panel ()
  (save-window-excursion
    (let ((source (generate-new-buffer " *panel-exit-source*"))
          (panel (generate-new-buffer " *panel-exit-terminal*"))
          (aipanel-sessions (make-hash-table :test #'eq))
          (aipanel-buffer-exited-hook nil))
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (aipanel-adopt-buffer panel (list :id source :source-buffer source)
                                  '(:agent (:id fx)))
            (aipanel-display-buffer panel 30)
            (cl-letf (((symbol-function 'run-at-time)
                       (lambda (_time _repeat function &rest args)
                         (apply function args))))
              (aipanel-process-exited panel "finished"))
            (should-not (buffer-live-p panel))
            (should-not (gethash source aipanel-sessions)))
        (dolist (buffer (list source panel))
          (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest aipanel-ordinary-display-restores-normal-terminal-input ()
  (with-temp-buffer
    (setq major-mode 'ghostel-mode)
    (setq-local evil-local-mode t
                ghostel--input-mode 'char)
    (let ((ghostel-char-mode-map (make-sparse-keymap)))
      (define-key ghostel-char-mode-map (kbd "C-p") #'ghostel--send-event)
      (define-key ghostel-char-mode-map (kbd "C-x") #'ghostel--send-event)
      (cl-letf (((symbol-function 'get-buffer-process)
                 (lambda (_buffer) 'agent-process))
                ((symbol-function 'process-live-p)
                 (lambda (process) (eq process 'agent-process)))
                ((symbol-function 'evil-local-mode)
                 (lambda (_value) (setq evil-local-mode nil)))
                ((symbol-function 'ghostel-char-mode)
                 (lambda () (use-local-map ghostel-char-mode-map))))
        (myconfig-aipanel-activate)
        (should-not evil-local-mode)
        (should (eq (key-binding (kbd "C-p")) #'ghostel--send-event))
        (should (eq (key-binding (kbd "C-x")) #'ghostel--send-event))))))

(ert-deftest aipanel-ordinary-panel-follows-its-source-view ()
  (save-window-excursion
    (let ((source (generate-new-buffer " *panel-source-view*"))
          (other (generate-new-buffer " *panel-other-view*"))
          (panel (generate-new-buffer " *panel-side-view*"))
          (aipanel-sessions (make-hash-table :test #'eq)))
      (unwind-protect
          (progn
            (switch-to-buffer source)
            (with-current-buffer panel
              (setq-local aipanel-owner (list :source-buffer source)))
            (puthash source (buffer-name panel) aipanel-sessions)
            (cl-letf (((symbol-function 'get-buffer-process)
                       (lambda (buffer) (and (eq buffer panel) 'agent-process)))
                      ((symbol-function 'process-live-p)
                       (lambda (process) (eq process 'agent-process))))
              (let ((side (aipanel-display-buffer panel
                                                  (max window-min-width
                                                       (floor (* (frame-width) 0.3))))))
                (aipanel-sync-source-visibility)
                (should (window-live-p side))
                (select-window (window-main-window))
                (switch-to-buffer other)
                (aipanel-sync-source-visibility)
                (should-not (window-live-p side))
                (should (buffer-live-p panel))
                (switch-to-buffer source)
                (aipanel-sync-source-visibility)
                (should (get-buffer-window panel)))))
        (dolist (buffer (list source other panel))
          (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest aipanel-ordinary-selected-panel-stays-visible-beside-multiple-splits ()
  (save-window-excursion
    (let ((source (generate-new-buffer " *panel-split-source*"))
          (other (generate-new-buffer " *panel-split-other*"))
          (panel (generate-new-buffer " *panel-split-terminal*"))
          (aipanel-sessions (make-hash-table :test #'eq))
          (aipanel-window-change-hook nil))
      (unwind-protect
          (progn
            (delete-other-windows)
            (switch-to-buffer other)
            (let ((source-window (split-window-below)))
              (select-window source-window)
              (switch-to-buffer source)
              (with-current-buffer panel
                (setq-local aipanel-owner (list :source-buffer source)))
              (puthash source (buffer-name panel) aipanel-sessions)
              (cl-letf (((symbol-function 'get-buffer-process)
                         (lambda (buffer) (and (eq buffer panel) 'agent-process)))
                        ((symbol-function 'process-live-p)
                         (lambda (process) (eq process 'agent-process))))
                (let ((side (aipanel-display-buffer panel 24)))
                  (should (eq (selected-window) side))
                  (should-not (window-live-p (window-main-window)))
                  (should (eq (aipanel-source-window (selected-frame)) source-window))
                  (should (eq (atelier-main-window) source-window))
                  (aipanel-sync-source-visibility)
                  (should (window-live-p side))
                  (should (eq (window-buffer side) panel))
                  (should (= (length (atelier-main-windows)) 2))))))
        (dolist (buffer (list source other panel))
          (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest atelier-side-window-commands-return-to-last-selected-main-split ()
  (dolist (command '(myconfig-terminal atelier-file-browser))
    (save-window-excursion
      (let ((source (generate-new-buffer " *side-command-source*"))
            (panel (generate-new-buffer " *side-command-panel*"))
            (target (generate-new-buffer " *side-command-target*"))
            (atelier-file-browser-window-configurations nil)
            (atelier-navigator-window-configurations nil))
        (unwind-protect
            (progn
              (delete-other-windows)
              (let ((main (split-window-below)))
                (select-window main)
                (switch-to-buffer source)
                (let ((side (display-buffer-in-side-window panel '((side . right)))))
                  (select-window side)
                  (cl-letf (((symbol-function 'atelier-current-workspace)
                             (lambda (&rest _) '(:id "side" :name "side")))
                            ((symbol-function 'atelier-workspace-buffer-by-type)
                             (lambda (&rest _) target)))
                    (funcall command))
                  (should (eq (selected-window) main))
                  (should (eq (window-buffer main) target))
                  (if (eq command 'atelier-file-browser)
                      (should-not (window-live-p side))
                    (should (eq (window-buffer side) panel))))))
          (dolist (buffer (list source panel target))
            (when (buffer-live-p buffer) (kill-buffer buffer))))))))

(ert-deftest aipanel-ordinary-ghostel-keys-pass-through ()
  (let ((ghostel-char-mode-map (make-sparse-keymap)))
    (cl-letf (((symbol-function 'ghostel--define-terminal-keys)
               (lambda (map _exceptions)
                 (dolist (key '("C-x" "C-p"))
                   (define-key map (kbd key) #'ghostel--send-event)))))
      (myconfig-terminal-configure-char-keys))
    (with-temp-buffer
      (use-local-map ghostel-char-mode-map)
      (setq-local meta-prefix-char nil)
      (dolist (key '("C-x" "C-p"))
        (should (eq (key-binding (kbd key)) #'ghostel--send-event))))))

(provide 'test-emacs-aipanel-ordinary)
;;; test-emacs-aipanel-ordinary.el ends here
