;;; test-emacs-workspace-stacks.el --- Workspace stacks and views -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'ls-lisp)
(add-to-list 'load-path
             (expand-file-name "../dotfiles/emacs/.config/emacs/lisp/atelier/"
                               (file-name-directory (or load-file-name buffer-file-name))))
(require 'atelier-persist)
(require 'dired-atelier)
(dired-atelier-setup)
(atelier-navigator-setup)

(defmacro atelier-stacks-test (&rest body)
  "Run BODY with real windows and an isolated workspace, files and buffers."
  (declare (indent 0))
  `(let* ((root (make-temp-file "atelier-stacks-" t))
          (workspace (list :id "stacks-test" :name "stacks-test" :destination "local"
                           :path root :status 'running :entries nil))
          (atelier-workspaces (list workspace))
          (atelier-content-live-buffers (make-hash-table :test #'equal))
          (atelier-entry-owners (make-hash-table :test #'eq))
          (atelier-change-hook nil)
          (atelier-navigator-window-configurations nil)
          (atelier-navigator-selection-by-frame nil)
          (atelier-close-without-asking t)
          (ls-lisp-use-insert-directory-program nil)
          (old-selection (frame-parameter nil 'atelier-workspace-id))
          (old-buffers (buffer-list)))
     (unwind-protect
         (save-window-excursion
           (delete-other-windows)
           (set-window-parameter nil 'atelier-view-id nil)
           (atelier-select-workspace workspace)
           ;; Batch Emacs has real windows but no graphical display.  Only the
           ;; host display check is replaced; model, layout and commands are real.
           (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _) t)))
             ,@body))
       (set-frame-parameter nil 'atelier-workspace-id old-selection)
       (dolist (buffer (buffer-list))
         (unless (memq buffer old-buffers) (kill-buffer buffer)))
       (delete-directory root t))))

(ert-deftest atelier-workspace-stacks-file-browser-keeps-split-and-view ()
  (atelier-stacks-test
    (let* ((file (expand-file-name "example.txt" root))
           (_ (with-temp-file file (insert "example")))
           (original (atelier-open-file file workspace))
           (left (selected-window))
           (right (atelier-split-right))
           (view-id (window-parameter right 'atelier-view-id)))
      (atelier-file-browser)
      (should (= (length (atelier-main-windows)) 2))
      (should (eq (window-buffer left) original))
      (should (equal view-id (window-parameter right 'atelier-view-id)))
      (should (with-current-buffer (window-buffer right) (derived-mode-p 'dired-mode)))
      (should (= (length (atelier-workspace-stack workspace 'file)) 1))
      (should (= (length (atelier-workspace-stack workspace 'dired)) 1))
      (let ((explorer (window-buffer right)))
        (select-window left)
        (atelier-file-browser)
        (should (eq (window-buffer left) explorer))
        (should (eq (window-buffer right) explorer))
        (should (= (length (atelier-workspace-stack workspace 'dired)) 1))))))

(ert-deftest atelier-workspace-stacks-splitting-creates-no-content ()
  (atelier-stacks-test
    (let* ((buffer (generate-new-buffer "*scratch split*"))
           (_ (atelier-show-buffer buffer workspace))
           (contents (mapcar (lambda (content) (plist-get content :id))
                            (plist-get workspace :contents)))
           (first-id (window-parameter nil 'atelier-view-id))
           (second (atelier-split-below)))
      (should (eq (window-buffer second) buffer))
      (should-not (equal first-id (window-parameter second 'atelier-view-id)))
      (should (equal contents (mapcar (lambda (content) (plist-get content :id))
                                     (plist-get workspace :contents))))
      (should (= (length (atelier-workspace-view-entries workspace)) 2)))))

(ert-deftest atelier-workspace-stacks-independent-selections-reuse-hidden-buffers ()
  (atelier-stacks-test
    (let* ((one (expand-file-name "one.txt" root))
           (two (expand-file-name "two.txt" root)))
      (with-temp-file one (insert "one"))
      (with-temp-file two (insert "two"))
      (let* ((first (atelier-open-file one workspace))
             (left (selected-window))
             (right (atelier-split-right))
             (second (atelier-open-file two workspace)))
        (should (eq (window-buffer left) first))
        (should (eq (window-buffer right) second))
        (should (= (length (atelier-workspace-stack workspace 'file)) 2))
        (atelier-file-browser)
        (should (eq (atelier-open-file two workspace) second))
        (should (eq (window-buffer left) first))
        (should (= (length (atelier-workspace-stack workspace 'file)) 2))))))

;; Switching buffers puts the last used one on top, so the previous buffer
;; stays one step away in the navigator instead of returning to its old slot.
(ert-deftest atelier-workspace-stacks-order-buffers-by-last-use ()
  (atelier-stacks-test
    (let ((files (mapcar (lambda (name) (expand-file-name name root))
                         '("a.txt" "b.txt" "c.txt")))
          buffers)
      (dolist (file files)
        (with-temp-file file (insert file))
        (push (atelier-open-file file workspace) buffers))
      (setq buffers (nreverse buffers))
      (cl-flet ((order ()
                  (mapcar (lambda (content) (file-name-nondirectory (plist-get content :file)))
                          (atelier-workspace-stack workspace 'file)))
                (shown ()
                  (mapcar (lambda (content) (file-name-nondirectory (plist-get content :file)))
                          (atelier-entry-stack (atelier-current-entry)))))
        (should (equal (shown) '("c.txt" "b.txt" "a.txt")))
        (with-current-buffer (atelier-render-navigator)
          (goto-char (cl-find-if
                      (lambda (position)
                        (memq (car (get-text-property position 'atelier-navigator-target))
                              '(workspace-buffer workspace-owned-buffer)))
                      (atelier-navigator-positions)))
          (atelier-navigator-stack-next)
          (atelier-navigator-stack-next)
          (should (equal (order) '("c.txt" "b.txt" "a.txt")))
          (atelier-navigator-open))
        (should (eq (window-buffer) (nth 0 buffers)))
        (should (equal (order) '("a.txt" "c.txt" "b.txt")))
        (atelier-open-file (nth 1 files) workspace)
        (should (eq (window-buffer) (nth 1 buffers)))
        (should (equal (order) '("b.txt" "a.txt" "c.txt")))
        (should (equal (shown) '("b.txt" "a.txt" "c.txt")))))))

;; A stack past its limit closes its least recently used buffers, but keeps
;; any buffer a view still selects and any file with unsaved changes.
(ert-deftest atelier-workspace-stacks-limit-closes-least-recent-buffers ()
  (atelier-stacks-test
    (let ((atelier-stack-limit 2)
          (buffers (make-hash-table :test #'equal)))
      (cl-flet ((open (name)
                  (let ((file (expand-file-name name root)))
                    (with-temp-file file (insert name))
                    (puthash name (atelier-open-file file workspace) buffers)))
                (order ()
                  (mapcar (lambda (content) (file-name-nondirectory (plist-get content :file)))
                          (atelier-workspace-stack workspace 'file)))
                (live (name) (buffer-live-p (gethash name buffers))))
        (dolist (name '("a" "b" "c")) (open name))
        (should (equal (order) '("c" "b")))
        (should-not (live "a"))
        (with-current-buffer (gethash "b" buffers) (insert "unsaved"))
        (open "d")
        (should (equal (order) '("d" "b")))
        (should-not (live "c"))
        (should (live "b"))
        (with-current-buffer (gethash "b" buffers) (set-buffer-modified-p nil))
        ;; The left view keeps showing d while the right view moves on.
        (atelier-split-right)
        (open "e")
        (should (equal (order) '("e" "d")))
        (should-not (live "b"))
        (open "f")
        (should (equal (order) '("f" "d")))
        (should-not (live "e"))
        (should (live "d"))))))

(ert-deftest atelier-workspace-stacks-custom-type-uses-the-same-view-operation ()
  (atelier-stacks-test
    (let ((atelier-types (copy-tree atelier-types))
          (one (generate-new-buffer "stack-custom-one"))
          (two (generate-new-buffer "stack-custom-two")))
      (atelier-define-type 'custom
        :buffer-p (lambda (buffer) (string-prefix-p "stack-custom" (buffer-name buffer))))
      (atelier-show-buffer one workspace)
      (let ((left (selected-window))
            (right (atelier-split-right)))
        (atelier-show-buffer two workspace)
        (should (eq (window-buffer left) one))
        (should (eq (window-buffer right) two))
        (should (= (length (atelier-workspace-stack workspace 'custom)) 2))
        (should (= (length (atelier-entry-stack (atelier-current-entry))) 2))
        (atelier-show-buffer one workspace)
        (should (eq (window-buffer right) one))
        (should (= (length (atelier-workspace-stack workspace 'custom)) 2))))))

(ert-deftest atelier-workspace-stacks-close-shared-view-then-final-buffer ()
  (atelier-stacks-test
    (let ((buffer (generate-new-buffer "*scratch shared*")))
      (atelier-show-buffer buffer workspace)
      (atelier-split-right)
      (atelier-close-current-view)
      (should (= (length (atelier-main-windows)) 1))
      (should (buffer-live-p buffer))
      (should (= (length (plist-get workspace :contents)) 1))
      (atelier-close-current-view)
      (should-not (buffer-live-p buffer))
      (should-not (plist-get workspace :contents))
      (should-not (plist-get workspace :stacks)))))

(ert-deftest atelier-workspace-stacks-migration-and-round-trip-retain-hidden-content ()
  (atelier-stacks-test
    (let* ((legacy (list :version 10 :generation "legacy"
                         :current-workspace-id "stacks-test"
                         :workspaces
                         (list (list :id "stacks-test" :name "stacks-test"
                                     :destination "local" :path root :status 'running
                                     :entry-root-ids '("view")
                                     :entries '((:id "view" :parent-id nil :displayed t
                                                    :content-ids ("first" "second")))
                                     :contents '((:id "first" :type file :kind scratch
                                                      :persistent t :name "first" :contents "one")
                                                 (:id "second" :type file :kind scratch
                                                      :persistent t :name "second" :contents "two"))))))
           (before (copy-tree legacy))
           (migrated (atelier-validate-state legacy))
           (restored (atelier-workspace-runtime-copy (car (plist-get migrated :workspaces)))))
      (should (equal legacy before))
      (should (= (plist-get migrated :version) 12))
      (should (= (length (atelier-workspace-stack restored 'file)) 2))
      (should (equal (plist-get (car (plist-get restored :entries)) :content-id) "first"))
      (let ((atelier-model-workspace restored))
        (atelier-entry-remove restored (car (plist-get restored :entries)) t)
        (should-not (plist-get restored :entries))
        (let ((flat (atelier-workspace-persistent-copy restored)))
          (should (= (length (plist-get flat :contents)) 2))
          (should (atelier-validate-state
                   (list :version 11 :generation "round-trip" :workspaces (list flat)))))))))

;; An adapter may be missing, as when its package is not installed; its saved
;; buffers must survive loading, or the next save would drop the whole state.
(ert-deftest atelier-workspace-stacks-keep-a-type-no-adapter-registers ()
  (atelier-stacks-test
    (let* ((saved (list :version 12 :generation "unregistered"
                        :current-workspace-id "stacks-test"
                        :workspaces
                        (list (list :id "stacks-test" :name "stacks-test"
                                    :destination "local" :path root :status 'running
                                    :entry-root-ids '("view")
                                    :entries '((:id "view" :parent-id nil :displayed t
                                                    :stack-id "phantom-stack"
                                                    :content-id "phantom"))
                                    :stacks '((:id "phantom-stack" :type phantom
                                                   :content-ids ("phantom")))
                                    :contents '((:id "phantom" :type phantom :kind transient
                                                     :persistent t :name "panel"
                                                     :stack-id "phantom-stack"))))))
           (validated (atelier-validate-state saved))
           (restored (atelier-workspace-runtime-copy (car (plist-get validated :workspaces)))))
      (should-not (assq 'phantom atelier-types))
      (should (= (length (atelier-workspace-stack restored 'phantom)) 1))
      (should (equal (atelier-type-label 'phantom) "phantom"))
      (should (equal (plist-get (atelier-workspace-persistent-copy restored) :contents)
                     (plist-get (car (plist-get validated :workspaces)) :contents))))))

;; A mistake in a type definition fails where it is written, naming the property.
(ert-deftest atelier-workspace-stacks-type-definitions-reject-mistakes ()
  (let ((atelier-types (copy-tree atelier-types)))
    (should (eq (atelier-define-type 'notes :label "notes" :buffer-p #'always) 'notes))
    (should (equal (atelier-type-label 'notes) "notes"))
    (should (string-match-p ":buffer-predicate"
                            (cadr (should-error (atelier-define-type 'notes :buffer-predicate #'always)))))
    (should (string-match-p ":restore"
                            (cadr (should-error (atelier-define-type 'notes :restore "not a function")))))
    (should-error (atelier-define-type 'notes :label ""))
    (should (eq (atelier-type-get 'notes :buffer-p) #'always))))

(ert-deftest atelier-workspace-stacks-restart-visible-and-hidden-jobs-once-each ()
  (atelier-stacks-test
    (let ((atelier-types (copy-tree atelier-types))
          (starts 0))
      (atelier-define-type 'terminal
        :buffer-p (lambda (buffer) (string-prefix-p "*stack-job" (buffer-name buffer)))
        :capture (lambda (_buffer) (atelier-job-capture)))
      ;; This exercises the real process and job lifecycle, not Ghostel's PTY.
      (cl-labels ((start-job (name directory program args owner &optional _shell _agent type)
                    (let ((buffer (generate-new-buffer name))
                          (atelier-job-owner-workspace owner))
                      (cl-incf starts)
                      (with-current-buffer buffer (setq default-directory directory))
                      (make-process :name name :buffer buffer :command (cons program args) :noquery t)
                      (atelier-register-job-buffer buffer nil directory (cons program args)
                                                   nil nil type)
                      buffer)))
        (let* ((one (start-job "*stack-job-one*" root "/bin/sh" '("-c" "sleep 30") workspace
                              nil nil 'terminal))
               (two (start-job "*stack-job-two*" root "/bin/sh" '("-c" "sleep 30") workspace
                              nil nil 'terminal))
               (atelier-job-start-function #'start-job))
          (atelier-show-buffer one workspace)
          (atelier-split-right)
          (atelier-show-buffer (generate-new-buffer "*scratch job view*") workspace)
          (should (= (length (atelier-workspace-stack workspace 'terminal)) 2))
          (should (= (length (atelier-build-restart-plan workspace)) 2))
          (should (= (length (cl-remove-if-not
                              (lambda (content) (plist-get content :job))
                              (plist-get (atelier-workspace-persistent-copy workspace) :contents))) 2))
          (atelier-restart-saved-jobs workspace)
          (should (= starts 4))
          (should-not (buffer-live-p one))
          (should-not (buffer-live-p two))
          (dolist (reference (atelier-workspace-job-entries workspace))
            (should (process-live-p (get-buffer-process (atelier-entry-live-buffer reference)))))
          (should (= (length (atelier-build-restart-plan workspace)) 2)))))))

(ert-deftest atelier-workspace-stacks-transfer-requires-unassignment-and-preserves-membership ()
  (atelier-stacks-test
    (let* ((destination (list :id "destination" :name "destination" :destination "local"
                              :path root :status 'running :entries nil))
           (detached (atelier-ensure-detached-workspace))
           (one (generate-new-buffer "*scratch stack-one*"))
           (two (generate-new-buffer "*scratch stack-two*")))
      (push destination atelier-workspaces)
      (atelier-show-buffer one workspace)
      (let* ((left (selected-window))
             (right (atelier-split-right))
             (_ (atelier-show-buffer two workspace))
             (left-view (atelier-entry-by-id workspace (window-parameter left 'atelier-view-id)))
             (right-view (atelier-current-entry))
             (stack-id (plist-get right-view :stack-id))
             (reference (atelier-content-reference workspace (atelier-entry-content right-view)))
             (members (copy-sequence (plist-get (atelier-workspace-stack-record workspace stack-id)
                                                 :content-ids)))
             (process (make-process :name "stack-transfer-process" :buffer two
                                    :command '("/bin/sh" "-c" "sleep 30") :noquery t)))
        (should-error (atelier-entry-move reference workspace detached) :type 'user-error)
        (atelier-view-unassign-stack workspace left-view)
        (should-error (atelier-entry-move reference workspace detached) :type 'user-error)
        (atelier-view-unassign-stack workspace right-view)
        (atelier-entry-move reference workspace detached)
        (should-not (atelier-workspace-stack-record workspace stack-id))
        (should (equal members (plist-get (atelier-workspace-stack-record detached stack-id) :content-ids)))
        (setq reference (atelier-entry-by-id detached (plist-get reference :content-id)))
        (atelier-entry-move reference detached destination)
        (should-not (atelier-workspace-stack-record detached stack-id))
        (should (equal members (plist-get (atelier-workspace-stack-record destination stack-id) :content-ids)))
        (should (cl-every (lambda (id)
                            (equal stack-id (plist-get (atelier-workspace-content destination id) :stack-id)))
                          members))
        (should (buffer-live-p one))
        (should (process-live-p process))
        (should-not (atelier-workspace-view-entries destination))
        (let ((view (atelier-entry-add destination (list :id "destination-view" :unassigned t) t)))
          (atelier-entry-activate-content view (plist-get reference :content-id))
          (should (equal stack-id (plist-get view :stack-id)))
          (should (eq two (atelier-entry-live-buffer view))))
        (should (atelier-validate-workspace-stacks workspace))
        (should (atelier-validate-workspace-stacks detached))
        (should (atelier-validate-workspace-stacks destination))))))

(ert-deftest atelier-workspace-stacks-occupied-destination-does-not-merge-buffers ()
  (atelier-stacks-test
    (let* ((destination (list :id "destination" :name "destination" :entries nil))
           (detached (atelier-ensure-detached-workspace))
           (one (generate-new-buffer "*scratch moving*"))
           (two (generate-new-buffer "*scratch staying*")))
      (push destination atelier-workspaces)
      (let ((reference (atelier-register-buffer one workspace)))
        (atelier-register-buffer two destination)
        (atelier-entry-move reference workspace detached)
        (let ((before (copy-tree atelier-workspaces)))
          (setq reference (atelier-entry-by-id detached (plist-get reference :content-id)))
          (should-error (atelier-entry-move reference detached destination) :type 'user-error)
          (should (equal before atelier-workspaces))
          (should (buffer-live-p one))
          (should (buffer-live-p two)))))))

(ert-deftest atelier-workspace-stacks-reject-standalone-content-and-type-changes ()
  (atelier-stacks-test
    (let* ((buffer (generate-new-buffer "*scratch membership*"))
           (reference (atelier-register-buffer buffer workspace)))
      (should (eq 'buffer (atelier-entry-value reference :type)))
      (should-error (atelier-entry-set-value reference :type 'file))
      (let* ((copy (atelier-workspace-runtime-copy (atelier-workspace-flat-copy workspace)))
             (content (car (plist-get copy :contents))))
        (atelier-plist-remove! content :stack-id)
        (should-error (atelier-validate-workspace-stacks copy))))))

(ert-deftest atelier-workspace-stacks-navigator-detaches-and-attaches-the-stack-in-stages ()
  (atelier-stacks-test
    (let* ((destination (list :id "destination" :name "destination" :destination "local"
                              :path root :status 'running :entries nil))
           (buffer (generate-new-buffer "*scratch navigator-stack*")))
      (push destination atelier-workspaces)
      (atelier-show-buffer buffer workspace)
      (let* ((view (atelier-current-entry))
             (view-id (plist-get view :id))
             (stack-id (plist-get view :stack-id))
             (members (copy-sequence (plist-get (atelier-workspace-stack-record workspace stack-id)
                                                 :content-ids))))
        (atelier-navigator)
        (atelier-navigator-detach (list 'workspace-buffer "stacks-test" 0 view-id))
         (should-not (atelier-entry-by-id workspace view-id))
        (should (atelier-workspace-stack-record workspace stack-id))
        (should (buffer-live-p buffer))
        (atelier-navigator-detach (list 'workspace-owned-buffer "stacks-test" stack-id))
        (should-not (atelier-workspace-stack-record workspace stack-id))
        (should (atelier-workspace-stack-record (atelier-detached-workspace) stack-id))
        (setq atelier-navigator-attach-source
              (list 'workspace-owned-buffer atelier-detached-workspace-name stack-id))
        (atelier-navigator-finish-attach '(workspace "destination"))
        (should (equal members (plist-get (atelier-workspace-stack-record destination stack-id) :content-ids)))
        (should-not (atelier-workspace-view-entries destination))
        (atelier-navigator-quit)
         (atelier-switch-workspace "destination")
         (atelier-show-buffer buffer destination)
         (let ((destination-view-id (window-parameter nil 'atelier-view-id)))
         (atelier-navigator)
        (setq atelier-navigator-attach-source (list 'workspace-owned-buffer "destination" stack-id))
         (atelier-navigator-finish-attach (list 'workspace-buffer "destination" 0 destination-view-id))
        (atelier-navigator-quit)
        (should (= (length (atelier-main-windows)) 1))
        (should (eq buffer (window-buffer)))
         (should (equal stack-id (plist-get (atelier-entry-by-id destination destination-view-id) :stack-id)))
         (should (equal members (plist-get (atelier-workspace-stack-record destination stack-id) :content-ids))))))))

(ert-deftest atelier-workspace-stacks-unassigned-split-closes-on-restore ()
  (atelier-stacks-test
    (let* ((buffer (generate-new-buffer "*scratch assigned*"))
           (_ (atelier-show-buffer buffer workspace))
           (left (selected-window))
           (right (atelier-split-right))
           (view (atelier-current-entry)))
      (atelier-view-unassign-stack workspace view)
      (atelier-display-entry-buffer view workspace right)
      (should-not (window-live-p right))
      (should (eq (window-buffer left) buffer))
      (should-not (atelier-entry-by-id workspace (plist-get view :id)))
      (should (buffer-live-p buffer)))))

(ert-deftest atelier-workspace-stacks-capture-under-navigator-keeps-views-openable ()
  (atelier-stacks-test
    (let* ((file (expand-file-name "example.txt" root))
           (_ (with-temp-file file (insert "example")))
           (buffer (atelier-open-file file workspace))
           (_ (atelier-capture-current-workspace))
           (view (car (atelier-workspace-displayed-entries workspace))))
      (atelier-navigator)
      ;; Any caller may capture while the navigator covers the frame.
      (atelier-capture-current-workspace)
      (atelier-navigator-open-content "stacks-test" (plist-get view :id)
                                      (plist-get view :content-id) 0)
      (should-not (assq (selected-frame) atelier-navigator-window-configurations))
      (should (eq (window-buffer) buffer))
      (should (equal (list (plist-get view :id))
                     (mapcar (lambda (entry) (plist-get entry :id))
                             (atelier-workspace-displayed-entries workspace)))))))

(ert-deftest atelier-workspace-stacks-last-detached-view-shows-another-stack ()
  (atelier-stacks-test
    (let* ((buffer (generate-new-buffer "*scratch detach*"))
           (_ (atelier-show-buffer buffer workspace))
           (view-id (window-parameter nil 'atelier-view-id))
           (directory (atelier-new-dired-buffer root nil workspace)))
      (atelier-register-buffer directory workspace nil 'dired)
      (atelier-navigator-detach (list 'workspace-buffer "stacks-test" 0 view-id))
      (atelier-navigator-quit)
      (should (eq (atelier-current-workspace) workspace))
      (should (eq (window-buffer) directory))
      (should-not (atelier-entry-by-id workspace view-id))
      (should (buffer-live-p buffer)))))

(ert-deftest atelier-workspace-stacks-last-detached-stack-switches-workspace ()
  (atelier-stacks-test
    (let* ((destination (list :id "destination" :name "destination" :destination "local"
                              :path root :status 'running :entries nil))
           (buffer (generate-new-buffer "*scratch detach-workspace*"))
           (other (generate-new-buffer "*scratch destination*")))
      (push destination atelier-workspaces)
      (atelier-register-buffer other destination)
      (atelier-show-buffer buffer workspace)
      (let ((view-id (window-parameter nil 'atelier-view-id)))
        (atelier-navigator-detach (list 'workspace-buffer "stacks-test" 0 view-id))
        (atelier-navigator-quit)
        (should (atelier-detached-workspace-p (atelier-current-workspace)))
        (should (buffer-live-p other))
        (should-not (atelier-entry-by-id workspace view-id))
        (should (buffer-live-p buffer))))))

(ert-deftest atelier-workspace-stacks-last-content-deletes-stack-and-frees-type ()
  (atelier-stacks-test
    (let* ((one (generate-new-buffer "*scratch first*"))
           (two (generate-new-buffer "*scratch second*"))
           (first (atelier-register-buffer one workspace))
           (second (atelier-register-buffer two workspace))
           (stack-id (plist-get first :stack-id)))
      (atelier-close-entry workspace first)
      (should (atelier-workspace-stack-record workspace stack-id))
      (should (buffer-live-p two))
      (atelier-close-entry workspace second)
      (should-not (atelier-entry-by-id workspace stack-id))
      (should-not (atelier-workspace-entries workspace))
      (should-not (plist-get (atelier-workspace-persistent-copy workspace) :stacks))
      (let* ((detached (atelier-ensure-detached-workspace))
             (new (atelier-register-buffer (generate-new-buffer "*scratch replacement*") detached)))
        (atelier-entry-move new detached workspace)
        (should (= 1 (length (atelier-workspace-stack workspace 'buffer))))))))

(ert-deftest atelier-workspace-stacks-restoration-discards-old-empty-stacks-and-views ()
  (atelier-stacks-test
    (let* ((snapshot (list :version 12 :generation "old-empty"
                           :workspaces
                           (list (list :id "stacks-test" :name "stacks-test"
                                       :destination "local" :path root :status 'running
                                       :stacks '((:id "empty" :type buffer :content-ids nil))
                                       :contents nil :entry-root-ids '("view")
                                       :entries '((:id "view" :parent-id nil :stack-id "empty"
                                                      :content-id nil :displayed t))))))
           (before (copy-tree snapshot))
           (saved (atelier-validate-state snapshot))
           (restored (car (plist-get saved :workspaces))))
      (should (equal snapshot before))
      (should-not (plist-get restored :stacks))
      (should-not (plist-get restored :entries))
      (should-not (plist-get restored :entry-root-ids)))))

(ert-deftest atelier-workspace-stacks-saving-transient-content-leaves-no-empty-stack ()
  (atelier-stacks-test
    (let* ((buffer (generate-new-buffer "transient-stack"))
           (_ (atelier-register-buffer buffer workspace))
           (saved (atelier-workspace-persistent-copy workspace)))
      (should (plist-get workspace :stacks))
      (should (buffer-live-p buffer))
      (should-not (plist-get saved :contents))
      (should-not (plist-get saved :stacks)))))

(ert-run-tests-batch-and-exit)
